### ISSUE TITLE
Create a Project Board 

### ISSUE THREAD

**Issue by honestaly** [TCArknight/T2K4E#35]
Simple Kanban is probably best, we aren't doing sprints.  But it would be nice to track issues/enhancements and be able to pu thtem into ToDo   / Doing / Done (and maybe a couple more) categories?

**Comment by honestaly** [comment]
Thanks... can I have permissions to add/move cards?  I think we should push the issues to cards so we know where we are on this.  I realize we're just us two... but I think it could help.

**Comment by honestaly** [comment]
Probably number 1 is to fix the way ammo works so that Mortars and other weapons that can load different kinds of ammo adjust their damage based on what is loaded into them.   Ideally when ammo is loaded into a gun, it fills the gun, and only depletes the ammo supply by the amount that fills it.

Number 2 would be to finish vehicles and make sure they work correctly.

At that point I cand o a lot of data entry for the vehicles, and swing back around to convert 1e/2e/2013 vehicles so there are more choices.  I can keep converting older editions... I just fell off because my last pull request was still sitting there.

Number 3 would be to then go over characters sheets with a fine toothed comb.

Number 4 would be to completely create a character and make sure journaling xp and progressing characters works.

Number 5 would be to test the combat tracker and see what needs to be fixed

Number 6 would be to create .STOCK npcs for encounter building.

Probably after 1-3 we could release, and bring 4-6 on as updates.

I get work... we're in the middle of a huge cloud project that we're supposed to get done before our code change freeze that's coming in about 3 weeks.

**Comment by TCArknight** [comment]
I've made some progress with vehicles. I want to get the tab set up for everything and then work on the Character sheet for them. :) 
As a result I've got the vehicle tab for the editor coming along too... Do you see anything missing for them?
I'll check this in and we can go from there.
    On Wednesday, December 1, 2021, 02:41:57 PM CST, Mark Tassin ***@***.***> wrote:  
 
 


Probably number 1 is to fix the way ammo works so that Mortars and other weapons that can load different kinds of ammo adjust their damage based on what is loaded into them. Ideally when ammo is loaded into a gun, it fills the gun, and only depletes the ammo supply by the amount that fills it.

Number 2 would be to finish vehicles and make sure they work correctly.

At that point I cand o a lot of data entry for the vehicles, and swing back around to convert 1e/2e/2013 vehicles so there are more choices. I can keep converting older editions... I just fell off because my last pull request was still sitting there.

Number 3 would be to then go over characters sheets with a fine toothed comb.

Number 4 would be to completely create a character and make sure journaling xp and progressing characters works.

Number 5 would be to test the combat tracker and see what needs to be fixed

Number 6 would be to create .STOCK npcs for encounter building.

Probably after 1-3 we could release, and bring 4-6 on as updates.

I get work... we're in the middle of a huge cloud project that we're supposed to get done before our code change freeze that's coming in about 3 weeks.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by honestaly** [comment]
Couple of things.
Not sure if it's just the test vehicles need to be updated, but they have a CUF rating... which vehicles don't ahve.   They also have a Hit capacity, a stress capacity, a defense and an Initiative.  And I'm not sure that a vehicle should have a vehicle as gear.

Vehicles take damage to Reliability (per component)
![image](https://user-images.githubusercontent.com/88744339/145717485-a19a5d38-c5b8-4909-9cd2-4826526fa047.png)

Probably components on a vehicle should be checkmarks in the editor.  i.e. not every vehicle has a radio.  The talent tab shouldn't show
